_target_: torch_brain.models.POYOPlus
sequence_length: 1.0
latent_step: 0.125
dim: 64
dim_head: 64
num_latents_per_step: 16
depth: 6
cross_heads: 2
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.2