_target_: torch_brain.models.POYO
sequence_length: 1.0
latent_step: 0.125
num_latents_per_step: 32
dim: 128
dim_head: 64
depth: 24
cross_heads: 4
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.2