defaults:
  - _default
  - dataset: test
  - model: [encoder_small, decoder]
  - sweep
  - _self_

load_from_checkpoint: true
fragment_checkpoint: true
checkpoint_path: /nethome/aandre8/torch_brain/examples/ndt2/logs/NDT2_IBL/checkpoints/
checkpoint_prefix: finetune

new_decoder: true
fragment_dataset: true
is_ssl: false


num_workers: 8
batch_size: 32

optimizer:
  scheduler: false
  lr: 1e-4 # [4e-5, 7e-5, 1e-4]
  accelerate_factor: 10
  weight_decay: 0.01  










