defaults:
  - _default
  - dataset: small_10
  - model: [encoder_small, decoder]
  - _self_

wandb:
  run_name: pretrain

num_workers: 8
batch_size: 128

mask_ratio: 0.5 # Into sweep
units_per_patch: 64 # Into sweep

model:
  dim: 128 # Into sweep

optimizer:
  scheduler: true
  lr: 0.0005 # Into sweep
  weight_decay: 0.01 # Into sweep
  start_factor: 0.1
  warmup_steps: 100
  decay_steps: 2500
  lr_min: 1e-6


bhvr_key: block

model:
  bhv_decoder:
    behavior_dim: 3
    task: classification


