# defaults used for training POYO
# this file needs to be combined with a model config and a dataset config

# Paths
data_root: ???
log_dir: ./logs

# Transforms
train_transform: null
eval_transform: null

# Training
seed: 42
epochs: 1000
batch_size: 128 # global batch size across all GPUs
num_workers: 4

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

# Logging
wandb:
  mode: online  # disabled, offline, or online
  entity: null
  project: poyo

# Checkpointing
ckpt_path: null  # for resuming training, or loading a model during finetuning
