defaults:
  - defaults.yaml
  - model: poyo_11.8M.yaml
  - _self_  # ensures current config overrides defaults

batch_size: 1024

dataset:
  _target_: datasets.poyo_mp.PoyoMPDataset

train_transform:
  _target_: torch_brain.transforms.UnitDropout
  max_units: 300
  min_units: 30
  mode_units: 100
  peak: 4

wandb:
  name: poyo_mp
