defaults:
  - base.yaml
  - model: poyo_single_session.yaml
  - dataset: allen_neuropixels.yaml
  - _self_

hydra:
  searchpath:
    - pkg://kirby/configs

train_transforms:
  - _target_: kirby.transforms.UnitDropout
    max_units: 1000
    min_units: 60
    mode_units: 300
    peak: 4
  - _target_: kirby.transforms.RandomCrop
    crop_len: 1.0

data_root: /kirby/processed/allen_all/

batch_size: 128
eval_epochs: 10

optim:
  base_lr: 1.5625e-5
  weight_decay: 0.0001

wandb:
  run_name: allen_neuropixels

backend_config: gpu_fp16
precision: bf16-mixed