- selection:
  - brainset: "pei_pandarinath_nlb_2021"
  config:
    readout:
      readout_id: cursor_velocity_2d
      metrics:
        - metric:
            _target_: torchmetrics.R2Score
      eval_interval: movement_phases.reach_period
