- selection:
    - brainset: "mc_maze_small"
  config:
    multitask_readout:
      - readout_id: arm_velocity_2d
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 1.0
          REACHING.REACH: 50.0
          REACHING.RETURN: 10.0
          REACHING.INVALID: 1.0
          REACHING.OUTLIER: 0.1
        metrics:
          - metric:
              _target_: torchmetrics.R2Score
              num_outputs: 2
            task: REACHING
