# 15 chewie sessions
- selection:
  - dandiset: perich_miller_population_2018
    sessions:
      - c_20131003_center_out_reaching
      - c_20131009_random_target_reaching
      - c_20131010_random_target_reaching
      - c_20131031_center_out_reaching
      - c_20150316_random_target_reaching
      - c_20151113_center_out_reaching
      - c_20151116_center_out_reaching
      - c_20160912_center_out_reaching
      - c_20161005_center_out_reaching
      - c_20161011_center_out_reaching
      - m_20140114_random_target_reaching
      - m_20140116_random_target_reaching
      - m_20140929_center_out_reaching
      - m_20150612_center_out_reaching
      - m_20150626_center_out_reaching
    exclude_sessions:
      - c_20161021_center_out_reaching  # holding out for testing
      - c_20161013_center_out_reaching  # holding out for testing