name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Setup virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install temporaldata
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python -m pip install --no-user --upgrade pip 
        pip install --no-user "temporaldata @ git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/neuro-galaxy/temporaldata@main#egg=temporaldata-0.1.1"
    - name: Install brainsets
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python -m pip install --no-user --upgrade pip 
        pip install --no-user "brainsets @ git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/neuro-galaxy/brainsets@main#egg=brainsets-0.1.0"
    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip 
        pip install -e ".[dev]" 
        pip install flake8 pytest
    - name: Install plugin
      run: |
        source venv/bin/activate
        pip install pytest-github-actions-annotate-failures
    - name: Test with pytest
      run: |
        source venv/bin/activate
        export WANDB_MODE=dryrun
        pytest tests/
